# Tensors

**PyTorch**는 **python** user 들에게 매우 친숙한 ML package이다. 

Code의 흐름 자체가 python에서의 그것과 매우 유사...똑같고, 또한 python의 numpy에서 data array를 다루는 방법과 PyTorch에서 tensor를 다루는 방법과 매우 유사하기 때문이다.

PyTorch의 Tensor는 Numpy의 np.array와 매우 비슷하다. 다만, 큰 차이가 있다면 np.array는 cpu에서만 처리할 수 있는 데이터 단위라면, PyTorch의 tensor는 GPU를 이용해서 처리가 가능하다는 점이다.

In [0]:
from __future__ import print_function
import torch

5x3 matrix를 만들어보자.

In [0]:
x = torch.empty(5,3)
print(x)

tensor([[3.1661e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 0.0000e+00, 0.0000e+00]])


In [0]:
x = torch.rand(5,3)
print(x)

tensor([[0.5155, 0.3030, 0.9955],
        [0.3051, 0.5404, 0.6806],
        [0.6276, 0.9301, 0.7287],
        [0.1237, 0.2064, 0.1500],
        [0.0215, 0.3749, 0.2426]])


In [0]:
x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [0]:
x = torch.tensor([5,3])
print(x.shape)
print(x)

torch.Size([2])
tensor([5, 3])


In [0]:
x = x.new_ones(5,3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [0]:
x = torch.rand_like(x, dtype=torch.float)

In [0]:
x

tensor([[0.0327, 0.7825, 0.0661],
        [0.6918, 0.6093, 0.7188],
        [0.9615, 0.2303, 0.1174],
        [0.4027, 0.1793, 0.5004],
        [0.3396, 0.6273, 0.3649]])

In [0]:
print(x.shape)
print(x.size())

torch.Size([5, 3])
torch.Size([5, 3])


In [0]:
y = torch.rand(5,3)

In [0]:
print(x+y)

tensor([[0.1769, 1.1981, 0.3232],
        [1.6468, 1.5800, 1.6549],
        [1.4218, 0.6512, 0.8240],
        [1.3715, 0.9266, 0.7172],
        [1.1145, 1.4018, 0.7611]])


In [0]:
print(torch.add(x,y))

tensor([[0.1769, 1.1981, 0.3232],
        [1.6468, 1.5800, 1.6549],
        [1.4218, 0.6512, 0.8240],
        [1.3715, 0.9266, 0.7172],
        [1.1145, 1.4018, 0.7611]])


In [0]:
result = torch.empty(5,3)

torch.add(x, y, out=result)

print(result)

tensor([[0.1769, 1.1981, 0.3232],
        [1.6468, 1.5800, 1.6549],
        [1.4218, 0.6512, 0.8240],
        [1.3715, 0.9266, 0.7172],
        [1.1145, 1.4018, 0.7611]])


In [0]:
x.add(y)
print(x)

tensor([[0.0327, 0.7825, 0.0661],
        [0.6918, 0.6093, 0.7188],
        [0.9615, 0.2303, 0.1174],
        [0.4027, 0.1793, 0.5004],
        [0.3396, 0.6273, 0.3649]])


In [0]:
print(x[:, 1])

tensor([0.7825, 0.6093, 0.2303, 0.1793, 0.6273])


In [0]:
x = torch.rand(4, 4)
y = x.view(16)
z = x.view(-1, 8)

print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


Tensor 에 element가 하나라면, <.item()>를 이용해서 value를 python number로 표시할 수 있다.

In [0]:
x = torch.rand(1)
print(x)
print(x.item())

tensor([0.7239])
0.7238510251045227


# Converting a Torch tensor to Numpy Array

In [0]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [0]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [0]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


# Converting Numpy Array to Torch Tensor

In [0]:
import numpy as np

In [0]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# CUDA Tensors

In [0]:
if torch.cuda.is_available(): #CUDA가 있는 경우에만 이 셀을 가동시키도록...
  device = torch.device('cuda')
  y = torch.ones_like(x, device=device)
  x = x.to(device)
  z = torch.add(x, y)
  print(z)
  print(z.to("cpu", torch.double))
  

tensor([1.7239], device='cuda:0')
tensor([1.7239], dtype=torch.float64)
